name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  check-links:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      id: lc
      uses: lycheeverse/lychee-action@v1.8.0
      with:
        # See cli args at https://github.com/lycheeverse/lychee#commandline-parameters
        # for excluded URLs, the checker seems to be stricter than Chrome
        args: >-
          --verbose --timeout 40 --insecure *.md
    - name: Fail if there were link errors
      run: exit ${{ steps.lc.outputs.exit_code }}
